/* This is dictionary.js
   Phase 2: Data Dictionary for Logic Output
   - This module defines the structure of the output generated by the rule engine.
   - UI will map keys and use this dictionary to display recommendations and explanations to the user.
   Phase 3: Placeholder Assets and Links
   - 
*/

(() => {
    // --- Placeholder assets ---
    /*const IMG = {
        tool: "assets/placeholders/tool.png",
        motor: "assets/placeholders/motor.png",
        bit: "assets/placeholders/bit.png",
        generic: "assets/placeholders/generic.png",
    };*/

    const LINK = {
        mwd: "#mwd",
        stabilizer: "#near-bit-stabilizer",
        shock: "#shock-vibration-tool",
        motor: "#motor",
        bit: "#bit",
        generic: "#",
    };

    // --- Output Dictionary ---
    // --- This dictionary amps the output keys from the rules; UI renders from this dictionary. ---
    const BHA_DICTIONARY ={
        // Tools
        MWD_RECOMMENDED: {
            title:"MWD Recommended",
            description: "Measeurement while drilling is recommended",
            link: LINK.mwd,
            category: "Tools",
            parameter: "MWD",
            tag: "Recommended",
            priority: 10,
        },
        MWD_NOT_RECOMMENDED: {
            title: "MWD Not Required",
            description: "",
            link: LINK.mwd,
            category: "Tools",
            parameter: "MWD",
            tag: "Not Selected",
            priority: 11,
        },

        NEAR_BIT_STABILIZER_RECOMMENDED: {
            title: "Near-bit Stabilizer Recommended",
            description: "Improve stability and reduce vibration.",
            link: LINK.stabilizer,
            category: "Tools",
            parameter: "Near-bit Stabilizer",
            tag: "Recommended",
            priority: 20,
        },
        NEAR_BIT_STABILIZER_NOT_RECOMMENDED: {
            title: "Near-bit Stabilizer Not Required",
            description: "",
            link: LINK.stabilizer,
            category: "Tools",
            parameter: "Near-bit Stabilizer",
            tag: "Not Selected",
            priority: 21,
        },

        SHOCK_VIBRATION_TOOL_RECOMMENDED: {
            title: "Shock/Vibration Tool Recommended",
            description: "Mitigate vibration risks.",
            link: LINK.shock,
            category: "Tools",
            parameter: "Shock/Vibration",
            tag: "Recommended",
            priority: 30,
        },
        SHOCK_VIBRATION_TOOL_NOT_RECOMMENDED: {
            title: "Shock/Vibration Tool Not Required",
            description: "",
            link: LINK.shock,
            category: "Tools",
            parameter: "Shock/Vibration",
            tag: "Not Selected",
            priority: 31,
        },

        // Motors
        MOTOR_HIGH_RPM_STANDARD_TORQUE: {
            title: "Motor: High RPM / Standard Torque",
            description: "Optimized for faster drilling where high rotary speed is suitable.",
            link: LINK.motor,
            category: "Motors",
            parameter: "Motor Type",
            tag: "Motor",
            priority: 40,
        },

        MOTOR_BALANCED_RPM_MEDIUM_TORQUE: {
            title: "Motor: Balanced RPM / Medium Torque",
            description: "Balanced option for general performance across mixed conditions.",
            link: LINK.motor,
            category: "Motors",
            parameter: "Motor Type",
            tag: "Motor",
            priority: 41,
        },

        MOTOR_LOW_RPM_HIGH_TORQUE: {
            title: "Motor: Low RPM / High Torque",
            description: "Best suited for harder formations requiring increased torque.",
            link: LINK.motor,
            category: "Motors",
            parameter: "Motor Type",
            tag: "Motor",
            priority: 42,
        },

        MOTOR_EVEN_WALL_THICKNESS_SUGGESTED: {
            title: "Even Wall Thickness Motor Recommended",
            description: "Suggested to improve durability under heavy load and stress conditions.",
            link: LINK.motor,
            category: "Motors",
            parameter: "Even Wall Thickness",
            tag: "Suggestion",
            priority: 50,
        },
        MOTOR_EVEN_WALL_THICKNESS_NOT_SUGGESTED: {
            title: "Even Wall Thickness Motor Not Required",
            description: "",
            link: LINK.motor,
            category: "Motors",
            parameter: "Even Wall Thickness",
            tag: "Not Selected",
            priority: 51,
        },

        // Bit
        BIT_AGG_HIGH: {
            title: "Bit Aggressiveness: High",
            description: "High aggressiveness can increase ROP in softer formations.",
            link: LINK.bit,
            category: "Bit",
            parameter: "Aggressiveness",
            tag: "Bit",
            priority: 60,
        },

        BIT_AGG_MEDIUM: {
            title: "Bit Aggressiveness: Medium",
            description: "Balanced aggressiveness for moderate formations and stability.",
            link: LINK.bit,
            category: "Bit",
            parameter: "Aggressiveness",
            tag: "Bit",
            priority: 61,
        },

        BIT_AGG_LOW: {
            title: "Bit Aggressiveness: Low",
            description: "Low aggressiveness to reduce vibration in hard/abrasive formations",
            link: LINK.bit,
            category: "Bit",
            parameter: "Aggressiveness",
            tag: "Bit",
            priority: 62,
        },

        BIT_CUTTER_DENSITY_HIGH: {
            title: "Cutter Density: High",
            description: "Higher cutter density is preferred in hard/abrasive formations.",
            link: LINK.bit,
            category: "Bit",
            parameter: "Cutter Density",
            tag: "Bit",
            priority: 70,
        },

        BIT_CUTTER_DENSITY_STANDARD: {
            title: "Cutter Density: Standard",
            description: "Standard cutter density is suitable for soft/medium formations.",
            link: LINK.bit,
            category: "Bit",
            parameter: "Cutter Density",
            tag: "Not Selected",
            priority: 71,
        },

        // Fallback
        UNKNOWN_OUTPUT_KEY: {
            title: "Unknown Output Key",
            description: "This key is not defined in the dictionary yet. Check missing entries.",
            link: LINK.generic,
            category: "Tools",
            parameter: "Debug",
            tag: "Debug",
            priority: 999,
        },
    };

    // --- All Outcomes per parameter (for UI display) ---
    const BHA_OUTCOMES = {
        Tools: {
            "MWD": [
                "MWD_RECOMMENDED",
                "MWD_NOT_RECOMMENDED"],
            "Near-bit Stabilizer": [
                "NEAR_BIT_STABILIZER_RECOMMENDED",
                "NEAR_BIT_STABILIZER_NOT_RECOMMENDED",],
            "Shock / Vibration": [
                "SHOCK_VIBRATION_TOOL_RECOMMENDED",
                "SHOCK_VIBRATION_TOOL_NOT_RECOMMENDED",],
        },
    
        Motors: {
            "Motor Type": [
                "MOTOR_HIGH_RPM_STANDARD_TORQUE",
                "MOTOR_BALANCED_RPM_MEDIUM_TORQUE",
                "MOTOR_LOW_RPM_HIGH_TORQUE",],
            "Even Wall Thickness": [
                "MOTOR_EVEN_WALL_THICKNESS_SUGGESTED",
                "MOTOR_EVEN_WALL_THICKNESS_NOT_SUGGESTED",],
        },
    
        Bit: {
          "Aggressiveness": [
                "BIT_AGG_HIGH",
                "BIT_AGG_MEDIUM",
                "BIT_AGG_LOW"],
          "Cutter Density": [
                "BIT_CUTTER_DENSITY_HIGH",
                "BIT_CUTTER_DENSITY_STANDARD"],
        },
    };

    window.BHA_DICTIONARY = BHA_DICTIONARY;
    window.BHA_OUTCOMES = BHA_OUTCOMES;

    // --- Validation Check ---
    const required = ["title", "description", "link", "category", "parameter", "priority"];
    for (const [key, item] of Object.entries(BHA_DICTIONARY)) {
        const missing = required.filter((f) => item?.[f] === undefined);
        if (missing.length) console.warn(`[dictionary.js] "${key}" missing fields: ${missing.join(", ")}`);
    }

    for (const [groupName, params] of Object.entries(BHA_OUTCOMES)) {
        for (const [paramName, keys] of Object.entries(params)) {
            keys.forEach((k) => {
                if (!BHA_DICTIONARY[k]) {
                    console.warn(`[dictionary.js] Catalog key missing in BHA_DICTIONARY: ${groupName} -> ${paramName} -> ${k}`);
                }
            });
        }
    }
})();