/* render.js
   Phase 2: UI Rendering Logic
   - This script handles the rendering of the output generated by the rule engine.
   Phase 3: Re-Render all outcomes per parameter
   - Uses the output keys and the dictionary to display recommendations and explanations to the user.
   - Highlights the recommended options from rules.js output.
   - Renders into the output area on the right column.
*/

(() => {
  const SHOW_DEBUG_KEY = false;

  const GROUP_ORDER = ["Tools", "Motors", "Bit"]; // Define the order of groups to display
  const PARAM_ORDER = {
    Tools: ["MWD", "Near-bit Stabilizer", "Shock/Vibration"],
    Motors: ["Motor Type", "Even Wall Thickness"],
    Bit: ["Cutter Density", "Aggressiveness"],
  };

  function createEl(tag, className = "", attrs = {}) {
    const el = document.createElement(tag);
    if (className) el.className = className;
    for (const [k, v] of Object.entries(attrs)) {
      if (v === null || v === undefined) continue;
      el.setAttribute(k, String(v));
    }
    return el;
  }

  function safeArray(value) {
    return Array.isArray(value) ? value : [];
  }

  function getDictionary() {
    const dict = window.BHA_DICTIONARY;
    if (!dict) {
      console.warn("[render.js] BHA_DICTIONARY not found. Did you load dictionary.js first?")
      return null;
    }
    return dict;
  }

  function getCatalog(dict) {
    // Preferred Phase 3: Build a catalog object from the dictionary for easier access during rendering
    const catalog = window.BHA_OUTCOMES;
    if (catalog && typeof catalog === "object") return catalog;

    // Fallback: derive from dictionary entries
    const derived = {};
    for (const [key, item] of Object.entries(dict)) {
      if (!item || key === "UNKNOWN_OUTPUT_KEY") continue;

      const group = item.category || "Tools";
      const param = item.parameter || "General";

      derived[group] ??= {};
      derived[group][param] ??= [];
      derived[group][param].push(key);
    }

    // Sort each parameter group by priority
    for (const group of Object.keys(derived)) {
      for (const param of Object.keys(derived[group])){
        derived[group][param].sort((a, b) => (dict[a]?.priority ?? 9999) - (dict[b]?.priority ?? 9999));
      }
    }

    return derived;
  }

  function buildSelectedSet(output) {
    const keysObj = output?.keys || {}
    const selected = new Set();
    
    safeArray(keysObj.Tools).forEach((keys) => selected.add(keys));
    safeArray(keysObj.Motors).forEach((keys) => selected.add(keys));
    safeArray(keysObj.Bit).forEach((keys) => selected.add(keys));

    return selected;
  }

  function isStrongSelection(item, key) {
    const category = item?.category || "";
    if (category === "Tools") {
      return key.endsWith("_RECOMMENDED") && !key.includes("NOT");
    }
    return true;
  }

  function shouldShowRecommendedBadge(key, selected) { // NEW
    if (!selected) return false;
    return !key.includes("NOT");
  }

  function buildCard(item, key, selectedSet) {
    // card shape stays fixed and add a class for highlight
    const selected = selectedSet.has(key);
    const strong = selected && isStrongSelection(item, key);

    const card = createEl(
      "article",
      `card shadow-sm border-0 rounded-4 h-100 overflow-hidden rec-card${selected ? " is-selected is-strong" : ""}`,
      { "data-key": key }
    );

    const body = createEl("div", "card-body d-flex gap-3 align-items-start");

    /* Image
    const imgWrap = createEl("div", "flex-shrink-0 rounded-3 overflow-hidden");
    imgWrap.style.width = "56px";
    imgWrap.style.height = "56px";

    const img = createEl("img", "d-block w-100 h-100", {
      src: item.image || "",
      alt: "",
      loading: "lazy",
    });
    img.style.objectFit = "cover";
    imgWrap.appendChild(img);*/

    // Content
    const content = createEl("div", "flex-grow-1");
    content.style.minWidth = "0";

    const topRow = createEl("div", "d-flex align-items-start justify-content-between gap-2");
    const h = createEl("h3", "h6 fw-semibold mb-1 text-break");
    h.textContent = item.title || key;
    topRow.appendChild(h);

    if (shouldShowRecommendedBadge(key, selected)) {
      const badge = createEl("span", "badge text-bg-light border flex-shrink-0");
      badge.textContent = "Recommended";
      topRow.appendChild(badge);
    }

    const desc = createEl("p", "text-secondary small mb-2 text-break");
    desc.textContent = item.description || "";
    content.appendChild(topRow);
    if(item.description) content.appendChild(desc);

    if (item.link && item.link !== "#") {
      const link = createEl("a", "link-primary small text-decoration-none", {
        href: item.link,
        target: "_blank",
        rel: "noopener noreferrer",
      });
      link.textContent = "Learn more";
      content.appendChild(link);
    }

    if (SHOW_DEBUG_KEY) {
      const debug = createEl("div", "small text-secondary mt-2 text-break");
      debug.style.opacity = "0.7";
      debug.textContent = `Key: ${key}`;
      content.appendChild(debug);
    }

    /*body.appendChild(imgWrap);*/
    body.appendChild(content);
    card.appendChild(body);

    return card;
  }

  function getParamColClass(groupName) {
    if (groupName === "Tools") return "col-12 col-lg-4";
    if (groupName === "Motors") return "col-12 col-lg-6";
    if (groupName === "Bit") return "col-12 col-lg-6";
    return "col-12 col-lg-6";
  }

  function renderGroupColumns (outputArea, dict, groupName, groupObj, selectedSet) {
    const groupHeader = createEl("div", "d-flex align-items-center justify-content-between mb-2");
    const h = createEl("h3", "h6 fw-semibold mb-0");
    h.textContent = groupName;
    groupHeader.appendChild(h);
    outputArea.appendChild(groupHeader);

    const row = createEl("div", "row g-4 mb-4 mx-0");

    const ordered = []
    const preferred = PARAM_ORDER[groupName] || [];

    for (const p of preferred) {
      if (groupObj?.[p] && !ordered.includes(p)) ordered.push(p);
    }

    for (const p of Object.keys(groupObj || {})) {
      if (!ordered.includes(p)) ordered.push(p);
    }

    for (const paramName of ordered) {
      const keys = groupObj?.[paramName];
      if (!keys) continue;

      const col = createEl("div", `${getParamColClass(groupName)} px-1`);
      col.style.minWidth = "0";

      const title = createEl("div", "small text-secondary fw-semibold mb-2");
      title.textContent = paramName;
      col.appendChild(title);

      const stack = createEl("div", "vstack gap-3");
      const list = safeArray(keys)
          .filter(Boolean)
          .slice()
          .sort((a,b) => (dict[a]?.priority ?? 9999) - (dict[b]?.priority ?? 9999));
      
      for (const key of list) {
        const item = dict[key] || dict.UNKNOWN_OUTPUT_KEY || { title: key, description: "", /*image: "",*/ link: "#", tag: "Debug" };
        stack.appendChild(buildCard(item, key, selectedSet));
      }

      col.appendChild(stack);
      row.appendChild(col);
    }
    outputArea.appendChild(row);
  }

  function renderEmpty(outputArea) {
    const box = createEl("div", "text-center text-secondary py-5");
    box.innerHTML = `
      <div class="mb-2 fw-semibold">No dictionary outcomes found</div>
      <div class="small">Check dictionary.js to ensure BHA_DICTIONARY and BHA_OUTCOMES are defined.</div>
    `;
    outputArea.appendChild(box);
  }

  // Public API
  window.renderOutputs = function renderOutputs(output) {
    const outputArea = document.getElementById("outputArea");
    if (!outputArea) {
      console.warn('[render.js] #outputArea not found. Add <div id="outputArea"></div> to your right column.');
      return;
    }

    const dict = getDictionary();
    if (!dict) return;

    const catalog = getCatalog(dict);
    const selectedSet = buildSelectedSet(output);

    outputArea.innerHTML = "";

    const hasAnyGroup = GROUP_ORDER.some((g) => catalog && catalog[g] && Object.keys(catalog[g]).length);

    if (!hasAnyGroup) {
      renderEmpty(outputArea);
      return;
    }

    for (const groupName of GROUP_ORDER) {
      const groupObj = catalog[groupName];
      if (!groupObj || !Object.keys(groupObj).length) continue;

      renderGroupColumns(outputArea, dict, groupName, groupObj, selectedSet);
    }
  };
})();