/* render.js
   Phase 2: UI Rendering Logic
    This script handles the rendering of the output generated by the rule engine. 
*/

(() => {
    function $(selector, root = document) {
      return root.querySelector(selector);
    }
  
    function createEl(tag, className = "", attrs = {}) {
      const el = document.createElement(tag);
      if (className) el.className = className;
      for (const [k, v] of Object.entries(attrs)) {
        if (v === null || v === undefined) continue;
        el.setAttribute(k, String(v));
      }
      return el;
    }
  
    function safeArray(v) {
      return Array.isArray(v) ? v : [];
    }
  
    function titleCase(s) {
      return String(s)
        .replace(/_/g, " ")
        .toLowerCase()
        .replace(/\b\w/g, (m) => m.toUpperCase());
    }
  
    function getDictionary() {
      const dict = window.BHA_DICTIONARY;
      if (!dict) {
        console.warn("[render.js] BHA_DICTIONARY not found. Did you load dictionary.js first?");
        return null;
      }
      return dict;
    }
  
    function buildCard(item, key) {
      // Outer card
      const card = createEl("article", "card shadow-sm border-0 rounded-4 h-100");
      const body = createEl("div", "card-body d-flex gap-3");
  
      /* Image
      const imgWrap = createEl("div", "flex-shrink-0");
      const img = createEl("img", "rounded-3", {
        src: item.image || "",
        alt: item.title ? `${item.title} icon` : "Recommendation icon",
        loading: "lazy",
      });*/

      // Simple sizing
      img.style.width = "56px";
      img.style.height = "56px";
      img.style.objectFit = "cover";
      imgWrap.appendChild(img);
  
      // Content
      const content = createEl("div", "flex-grow-1");
      const topRow = createEl("div", "d-flex align-items-start justify-content-between gap-2");
  
      const h = createEl("h3", "h6 fw-semibold mb-1");
      h.textContent = item.title || key;
  
      topRow.appendChild(h);
  
      if (item.tag) {
        const tag = createEl("span", "badge text-bg-light border");
        tag.textContent = item.tag;
        topRow.appendChild(tag);
      }
  
      const desc = createEl("p", "text-secondary small mb-2");
      desc.textContent = item.description || "";
  
      content.appendChild(topRow);
      if (item.description) content.appendChild(desc);
  
      if (item.link && item.link !== "#") {
        const link = createEl("a", "link-primary small text-decoration-none", {
          href: item.link,
          target: "_blank",
          rel: "noopener noreferrer",
        });
        link.textContent = "Learn more";
        content.appendChild(link);
      }
  
      // Debug key
      const debug = createEl("div", "small text-secondary mt-2");
      debug.style.opacity = "0.7";
      debug.textContent = `Key: ${key}`;
      content.appendChild(debug);
  
      body.appendChild(imgWrap);
      body.appendChild(content);
      card.appendChild(body);
  
      return card;
    }
  
    function renderGroup(outputArea, dict, groupName, keys) {
      const cleaned = safeArray(keys).filter(Boolean);
      if (!cleaned.length) return;
  
      // Group header
      const header = createEl("div", "d-flex align-items-center justify-content-between mb-2");
      const h = createEl("h3", "h6 fw-semibold mb-0");
      h.textContent = titleCase(groupName);
      header.appendChild(h);
  
      outputArea.appendChild(header);
  
      // Grid of cards
      const row = createEl("div", "row g-3 mb-4");
  
      // Sort by dictionary priority
      cleaned.sort((a, b) => {
        const pa = dict[a]?.priority ?? 9999;
        const pb = dict[b]?.priority ?? 9999;
        return pa - pb;
      });
  
      for (const key of cleaned) {
        const item = dict[key] || dict.UNKNOWN_OUTPUT_KEY || { title: key, description: "", image: "", link: "#", tag: "Debug" };
  
        const col = createEl("div", "col-12 col-md-6");
        col.appendChild(buildCard(item, key));
        row.appendChild(col);
      }
  
      outputArea.appendChild(row);
    }
  
    function renderEmptyState(outputArea) {
      const box = createEl("div", "text-center text-secondary py-5");
      box.innerHTML = `
        <div class="mb-2 fw-semibold">No recommendations yet</div>
        <div class="small">Change inputs on the left to generate output keys.</div>
      `;
      outputArea.appendChild(box);
    }
  
    // Public API
    window.renderOutputs = function renderOutputs(output) {
      const outputArea = document.getElementById("outputArea");
      if (!outputArea) {
        console.warn('[render.js] #outputArea not found. Add <div id="outputArea"></div> to your right column.');
        return;
      }
  
      const dict = getDictionary();
      if (!dict) return;
  
      outputArea.innerHTML = "";
  
      const keysObj = output?.keys || {};
      const tools = safeArray(keysObj.tools);
      const motor = safeArray(keysObj.motor);
      const bit = safeArray(keysObj.bit);
  
      const total = tools.length + motor.length + bit.length;
      if (!total) {
        renderEmptyState(outputArea);
        return;
      }
  
      renderGroup(outputArea, dict, "tools", tools);
      renderGroup(outputArea, dict, "motor", motor);
      renderGroup(outputArea, dict, "bit", bit);
    };
  })();